"""Release version guard (Requirement 10.7).

The Rule Engine keeps a **hand-curated** ``CHANGELOG.md``: every release section
(its added/changed/removed narrative) is written by a human before the release
is tagged, not generated by CI. The release contract therefore requires that the
Semantic Version being released **already has a curated section** in the
Changelog. If a release trigger specifies a Semantic Version that is *absent*
from ``CHANGELOG.md``, the run must fail and produce no Release Bundle — the
maintainer forgot to write the changelog entry.

This is the inverse of the original (auto-generated-changelog) contract: there,
CI generated the entry and so required the version to be *absent*. This module
now extracts the **presence** check into a small, testable unit so it can run as
an early CI ``version-guard`` job (before the build stage packages any bundle)
and be exercised directly by unit tests.

A version is considered "present" in the Changelog when the Changelog contains
a version section heading for it, i.e. a line of the form::

    ## [1.2.3] - 2025-01-15
    ## [1.2.3]

The comparison is on the exact Semantic Version string, tolerant of an optional
leading ``v`` (``v1.2.3`` and ``1.2.3`` are treated as the same version).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


class MissingVersionError(ValueError):
    """Raised when a release Semantic Version has no curated Changelog section.

    The Changelog is hand-curated, so a release must not proceed until its
    version section exists (fail-closed: no Release Bundle is produced).
    """

    def __init__(self, version: str, changelog_path: str | Path | None = None) -> None:
        self.version = version
        self.changelog_path = str(changelog_path) if changelog_path is not None else None
        location = f" in {self.changelog_path}" if self.changelog_path else ""
        super().__init__(
            f"Semantic Version {version!r} has no curated section{location}; "
            "add the CHANGELOG entry before releasing. Refusing to produce a "
            "Release Bundle."
        )


def normalize_version(version: str) -> str:
    """Return the bare Semantic Version, dropping an optional leading ``v``.

    ``"v1.2.3"`` and ``" 1.2.3 "`` both normalize to ``"1.2.3"``.
    """
    return version.strip().lstrip("v").strip()


def changelog_has_version(changelog_text: str, version: str) -> bool:
    """Return ``True`` if ``version`` already has a section in the Changelog.

    A version is present when the Changelog contains a heading line of the form
    ``## [<version>]`` (optionally followed by a date). The check tolerates an
    optional leading ``v`` on the requested version.
    """
    normalized = normalize_version(version)
    if not normalized:
        return False
    # Match a Markdown version heading: "## [<version>]" at line start,
    # allowing an optional leading "v" on the recorded version.
    pattern = r"^##\s*\[v?" + re.escape(normalized) + r"\]"
    return re.search(pattern, changelog_text, re.MULTILINE) is not None


def assert_version_present(changelog_path: str | Path, version: str) -> None:
    """Raise :class:`MissingVersionError` if ``version`` has no curated section.

    The Changelog is hand-curated: the release version's section must already
    exist. A missing Changelog file, or a Changelog without the version's
    heading, is a fail-closed error (no Release Bundle is produced).
    """
    path = Path(changelog_path)
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise MissingVersionError(normalize_version(version), path) from exc
    if not changelog_has_version(text, version):
        raise MissingVersionError(normalize_version(version), path)


def main(argv: list[str] | None = None) -> int:
    """CLI entry point for the CI ``version-guard`` job.

    Usage::

        python -m rule_engine.version_guard <changelog_path> <version>
        python -m rule_engine.version_guard --triple [<repo_root>]

    Exits ``0`` when the version already has a curated Changelog section (safe to
    build a Release Bundle) and ``1`` when the version is absent (fail-closed: no
    bundle is produced, the maintainer must add the entry first).

    ``--triple`` checks the other half of the release contract (v1.6.0): that
    ``VERSION``, ``pyproject.toml`` and the newest ``CHANGELOG.md`` section all
    name the same version. Exits ``1`` naming each source's value when they
    disagree.
    """
    args = list(sys.argv[1:] if argv is None else argv)
    if args and args[0] == "--triple":
        if len(args) > 2:
            print(
                "usage: python -m rule_engine.version_guard --triple [<repo_root>]",
                file=sys.stderr,
            )
            return 2
        repo_root = args[1] if len(args) == 2 else "."
        try:
            agreed = assert_version_triple_consistent(repo_root)
        except VersionMismatchError as exc:
            print(f"BLOCKING: {exc}", file=sys.stderr)
            return 1
        print(
            f"OK: VERSION, pyproject.toml and CHANGELOG.md all agree on "
            f"{agreed!r}."
        )
        return 0
    if len(args) != 2:
        print(
            "usage: python -m rule_engine.version_guard <changelog_path> <version>\n"
            "   or: python -m rule_engine.version_guard --triple [<repo_root>]",
            file=sys.stderr,
        )
        return 2
    changelog_path, version = args
    try:
        assert_version_present(changelog_path, version)
    except MissingVersionError as exc:
        print(f"BLOCKING: {exc}", file=sys.stderr)
        return 1
    print(
        f"OK: Semantic Version {normalize_version(version)!r} has a curated "
        f"section in {changelog_path}; safe to build the Release Bundle."
    )
    return 0


# ---------------------------------------------------------------------------
# Version-triple consistency (v1.6.0)
# ---------------------------------------------------------------------------
#
# The released version is recorded in THREE places and they drifted: at 1.5.4 the
# working tree carried ``VERSION`` = 1.5.3, ``pyproject.toml`` = 1.5.4, and a top
# CHANGELOG heading of 1.5.4. CI rewrites ``VERSION`` at tag time, so the stale
# file never broke a release — which is exactly why nothing surfaced the drift.
# These helpers make the triple a checked contract: one source disagreeing is a
# blocking error, not a silent inconsistency a reader has to reconcile by hand.

#: The three files that must agree on the version being released.
VERSION_FILE = "VERSION"
PYPROJECT_FILE = "pyproject.toml"
CHANGELOG_FILE = "CHANGELOG.md"

# ``version = "1.2.3"`` in the [project] table. Matched line-anchored so a
# dependency pin like ``jsonschema>=4.18`` can never be mistaken for it.
_PYPROJECT_VERSION_RE = re.compile(
    r'^version\s*=\s*["\']([^"\']+)["\']', re.MULTILINE
)

# The first ``## [1.2.3]`` heading in the Changelog is the most recent release,
# because the Changelog is kept in reverse chronological order.
_CHANGELOG_HEADING_RE = re.compile(r"^##\s*\[v?([0-9][^\]]*)\]", re.MULTILINE)


class VersionMismatchError(ValueError):
    """Raised when ``VERSION``, ``pyproject.toml`` and ``CHANGELOG.md`` disagree.

    Carries the per-source values so the error names exactly which file is out
    of step, rather than only reporting that something is wrong.
    """

    def __init__(self, versions: dict[str, str | None]) -> None:
        self.versions = dict(versions)
        detail = ", ".join(
            f"{name}={value!r}" for name, value in sorted(versions.items())
        )
        super().__init__(
            "release version sources disagree: "
            f"{detail}. Bring all three into agreement before releasing."
        )


def read_version_file(repo_root: str | Path) -> str | None:
    """Return the bare version recorded in ``VERSION``, or ``None`` if absent."""
    path = Path(repo_root) / VERSION_FILE
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None
    stripped = text.strip()
    return normalize_version(stripped) if stripped else None


def read_pyproject_version(repo_root: str | Path) -> str | None:
    """Return the ``[project] version`` from ``pyproject.toml``, or ``None``."""
    path = Path(repo_root) / PYPROJECT_FILE
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None
    match = _PYPROJECT_VERSION_RE.search(text)
    return normalize_version(match.group(1)) if match else None


def latest_changelog_version(changelog_text: str) -> str | None:
    """Return the version of the Changelog's newest section, or ``None``.

    The Changelog is reverse chronological, so the FIRST ``## [x.y.z]`` heading
    is the most recent release.
    """
    match = _CHANGELOG_HEADING_RE.search(changelog_text)
    return normalize_version(match.group(1)) if match else None


def read_changelog_version(repo_root: str | Path) -> str | None:
    """Return the newest version section recorded in ``CHANGELOG.md``."""
    path = Path(repo_root) / CHANGELOG_FILE
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None
    return latest_changelog_version(text)


def version_triple(repo_root: str | Path) -> dict[str, str | None]:
    """Return the version recorded by each of the three sources."""
    return {
        VERSION_FILE: read_version_file(repo_root),
        PYPROJECT_FILE: read_pyproject_version(repo_root),
        CHANGELOG_FILE: read_changelog_version(repo_root),
    }


def assert_version_triple_consistent(repo_root: str | Path) -> str:
    """Return the agreed version, or raise :class:`VersionMismatchError`.

    All three sources must be present and equal. A missing source counts as a
    disagreement (fail-closed), so a deleted ``VERSION`` file cannot quietly
    reduce the contract to two sources.
    """
    versions = version_triple(repo_root)
    distinct = set(versions.values())
    if None in distinct or len(distinct) != 1:
        raise VersionMismatchError(versions)
    return distinct.pop()


# The module-run guard lives at the END of the file: ``python -m
# rule_engine.version_guard`` executes the module top-to-bottom, so a guard
# placed mid-file would call ``main()`` before the definitions below it had run.
if __name__ == "__main__":
    raise SystemExit(main())
