"""Release version guard (Requirement 10.7).

The Rule Engine keeps a **hand-curated** ``CHANGELOG.md``: every release section
(its added/changed/removed narrative) is written by a human before the release
is tagged, not generated by CI. The release contract therefore requires that the
Semantic Version being released **already has a curated section** in the
Changelog. If a release trigger specifies a Semantic Version that is *absent*
from ``CHANGELOG.md``, the run must fail and produce no Release Bundle — the
maintainer forgot to write the changelog entry.

This is the inverse of the original (auto-generated-changelog) contract: there,
CI generated the entry and so required the version to be *absent*. This module
now extracts the **presence** check into a small, testable unit so it can run as
an early CI ``version-guard`` job (before the build stage packages any bundle)
and be exercised directly by unit tests.

A version is considered "present" in the Changelog when the Changelog contains
a version section heading for it, i.e. a line of the form::

    ## [1.2.3] - 2025-01-15
    ## [1.2.3]

The comparison is on the exact Semantic Version string, tolerant of an optional
leading ``v`` (``v1.2.3`` and ``1.2.3`` are treated as the same version).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


class MissingVersionError(ValueError):
    """Raised when a release Semantic Version has no curated Changelog section.

    The Changelog is hand-curated, so a release must not proceed until its
    version section exists (fail-closed: no Release Bundle is produced).
    """

    def __init__(self, version: str, changelog_path: str | Path | None = None) -> None:
        self.version = version
        self.changelog_path = str(changelog_path) if changelog_path is not None else None
        location = f" in {self.changelog_path}" if self.changelog_path else ""
        super().__init__(
            f"Semantic Version {version!r} has no curated section{location}; "
            "add the CHANGELOG entry before releasing. Refusing to produce a "
            "Release Bundle."
        )


def normalize_version(version: str) -> str:
    """Return the bare Semantic Version, dropping an optional leading ``v``.

    ``"v1.2.3"`` and ``" 1.2.3 "`` both normalize to ``"1.2.3"``.
    """
    return version.strip().lstrip("v").strip()


def changelog_has_version(changelog_text: str, version: str) -> bool:
    """Return ``True`` if ``version`` already has a section in the Changelog.

    A version is present when the Changelog contains a heading line of the form
    ``## [<version>]`` (optionally followed by a date). The check tolerates an
    optional leading ``v`` on the requested version.
    """
    normalized = normalize_version(version)
    if not normalized:
        return False
    # Match a Markdown version heading: "## [<version>]" at line start,
    # allowing an optional leading "v" on the recorded version.
    pattern = r"^##\s*\[v?" + re.escape(normalized) + r"\]"
    return re.search(pattern, changelog_text, re.MULTILINE) is not None


def assert_version_present(changelog_path: str | Path, version: str) -> None:
    """Raise :class:`MissingVersionError` if ``version`` has no curated section.

    The Changelog is hand-curated: the release version's section must already
    exist. A missing Changelog file, or a Changelog without the version's
    heading, is a fail-closed error (no Release Bundle is produced).
    """
    path = Path(changelog_path)
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise MissingVersionError(normalize_version(version), path) from exc
    if not changelog_has_version(text, version):
        raise MissingVersionError(normalize_version(version), path)


def main(argv: list[str] | None = None) -> int:
    """CLI entry point for the CI ``version-guard`` job.

    Usage::

        python -m rule_engine.version_guard <changelog_path> <version>

    Exits ``0`` when the version already has a curated Changelog section (safe to
    build a Release Bundle) and ``1`` when the version is absent (fail-closed: no
    bundle is produced, the maintainer must add the entry first).
    """
    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) != 2:
        print(
            "usage: python -m rule_engine.version_guard <changelog_path> <version>",
            file=sys.stderr,
        )
        return 2
    changelog_path, version = args
    try:
        assert_version_present(changelog_path, version)
    except MissingVersionError as exc:
        print(f"BLOCKING: {exc}", file=sys.stderr)
        return 1
    print(
        f"OK: Semantic Version {normalize_version(version)!r} has a curated "
        f"section in {changelog_path}; safe to build the Release Bundle."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
